### ISSUE TITLE
Synchronisation

### ISSUE THREAD

**Issue by ransona** [neurogears/ranson-rig#16]
to be discussed - exactly how to sync bonsai stuff with other stuff in experiment (during analysis)

**Comment by glopesdev** [comment]
I believe we discussed this before, but there are essentially two ways to do this, either sending a TTL to the Harp board which will be automatically timestamped and logged, or configure a TTL output from the board to the external device. The ranson-rig workflow logs all input and output command TTLs to/from the board already so either case is already covered.
