### ISSUE TITLE
expID naming convention and data storage location

### ISSUE THREAD

**Issue by ransona** [neurogears/ranson-rig#30]
The naming convention for experiment IDs should be:

2016-10-14_09_CFAP049

i.e. 
2016-10-14 - is the date
09 - is the experiment number for that animal on that date
CFAP049 - is the animal identifier

For this example the folder structure should be:

c:\local_repository\CFAP049\2016-10-14_09_CFAP049\

The data also needs to be copied to a remote server at the end of each trial so that we can do adaptive training on a trial by trial basis during behavioural experiments etc. 

How best to specify the local and remote storage path? I suggest we specify this at our end at experiment start - i.e. we put it in the meta data?

**Comment by glopesdev** [comment]
fixed with #37
