### ISSUE TITLE
stimulus doesn't display properly on ~half of each screen

### ISSUE THREAD

**Issue by ransona** [neurogears/ranson-rig#33]
The stimulus does not extend beyond approximately -90 and +90 in the x direction on the screen. For example this is a screen grab of a stimulus which should be circular - notice the clipping on the left and right ... not sure if that grey vertical line is also visible on the screen
![image](https://user-images.githubusercontent.com/7849066/117840441-73989380-b27c-11eb-8f4d-58490f51f79a.png)

**Comment by glopesdev** [comment]
Fixed with 900014a0c02e2240a0891efcb2c68953b5df4b32.
