### ISSUE TITLE
too many files produced for convenient handling

### ISSUE THREAD

**Issue by ransona** [neurogears/ranson-rig#41]
Google drive handles sync of large numbers of small files prohibatively prohibitively inefficiently. We therefore need the trial information csvs and the Responses csvs to be concatinated (as well as being stored as individual files for replay).

**Comment by glopesdev** [comment]
How would you suggest concatenating these CSVs in a way that allows splitting individual trials? The simplest possibility might be to add an extra column in the beginning of the file specifying the trial index when the row was logged.

**Comment by ransona** [comment]
Yes a column for trial index would be perfect I think!
