### ISSUE TITLE
Race condition when creating trial metadata file

### ISSUE THREAD

**Issue by ransona** [neurogears/ranson-rig#43]
Sometimes there seems to be one more trial file than expected. For example in this experiment:
\\AR-LAB-NAS1\DataServer\Remote_Repository\TEST\2021-07-09_05_TEST
I did 9 trials but there are 10 trial files (i.e. 0 - 9). The final one ('2021-07-09_05_TEST_00009.csv') does not contain trial parameters.
![image](https://user-images.githubusercontent.com/7849066/125085935-67d61b80-e0cb-11eb-93f8-808ddb016471.png)

**Comment by ransona** [comment]
I tested some more and it seems to be random whether it makes more or less trial parameter files.

**Comment by glopesdev** [comment]
I think I understand now what is happening and there was actually a race condition preventing the proper creation and logging of trial metadata. Hopefully this will be fixed with the following commit.
